arm_group:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005 
  kinematics_solver_timeout: 0.005 
  position_only_ik: False # True - use only position IK, False - use both position and orientation IK